require('dotenv').config();
const bcrypt = require('bcryptjs');
const mongoose = require('mongoose');
const { connectDB, disconnectDB } = require('./config/db');

const User = require('./models/User');
const Asset = require('./models/Asset');
const Inspection = require('./models/Inspection');
const Maintenance = require('./models/Maintenance');
const LifecycleEvent = require('./models/LifecycleEvent');

const seedData = async () => {
  try {
    console.log('🧹 Clearing existing collections...');
    await User.deleteMany({});
    await Asset.deleteMany({});
    await Inspection.deleteMany({});
    await Maintenance.deleteMany({});
    await LifecycleEvent.deleteMany({});

    console.log('👤 Seeding Users with RBAC roles...');
    const salt = await bcrypt.genSalt(10);
    const adminPasswordHash = await bcrypt.hash('Admin@123', salt);
    const inspectorPasswordHash = await bcrypt.hash('Inspector@123', salt);
    const officerPasswordHash = await bcrypt.hash('Officer@123', salt);

    const adminUser = await User.create({
      name: 'Rajesh Varma (Chief Executive Engineer)',
      email: 'admin@roadsetu.gov.in',
      passwordHash: adminPasswordHash,
      role: 'ADMIN',
      department: 'State Road Development Agency, Gujarat',
    });

    const inspectorUser = await User.create({
      name: 'Ananya Patel (Senior Field Inspector)',
      email: 'inspector.patel@roadsetu.gov.in',
      passwordHash: inspectorPasswordHash,
      role: 'FIELD_INSPECTOR',
      department: 'National Highway & Bridge Quality Audit Wing',
    });

    const officerUser = await User.create({
      name: 'Vikram Sharma (Superintending Maintenance Officer)',
      email: 'engineer.sharma@roadsetu.gov.in',
      passwordHash: officerPasswordHash,
      role: 'MAINTENANCE_OFFICER',
      department: 'Transportation Rehabilitation & Maintenance Cell',
    });

    console.log('🌉 Seeding 25 Transportation Assets (Roads, Highways, Bridges)...');

    // Primary Demo Asset: BR-014 Sabarmati Connector Bridge
    const primaryBridge = await Asset.create({
      assetId: 'BR-014',
      assetCode: 'GJ-AHM-BR-014',
      assetType: 'BRIDGE',
      name: 'Sabarmati Connector Bridge',
      description: 'Major arterial 6-lane prestressed concrete connector bridge spanning the Sabarmati River connecting Ashram Road to Riverfront West.',
      department: 'Ahmedabad Municipal Corporation Bridge Wing',
      state: 'Gujarat',
      district: 'Ahmedabad',
      area: 'Sabarmati Riverfront West',
      location: {
        latitude: 23.0374,
        longitude: 72.5714,
        address: 'Sabarmati Riverfront, Ashram Rd Corridor, Ahmedabad',
      },
      assetSpecificDetails: {
        bridgeNumber: 'BR-014-SBR',
        bridgeName: 'Sabarmati Connector Bridge',
        crossingType: 'RIVER',
        riverOrCrossing: 'Sabarmati River',
        lengthMeters: 620,
        widthMeters: 28.5,
        laneCount: 6,
        structuralType: 'RCC',
        loadCapacityTons: 120,
      },
      condition: 'POOR',
      status: 'UNDER_MAINTENANCE',
      constructionDate: new Date('2021-04-15'),
      operationalDate: new Date('2023-08-15'),
      estimatedCost: 850000000, // 85 Crore INR
      lastInspectionDate: new Date('2025-01-10'),
      nextInspectionDate: new Date('2025-07-10'),
      createdBy: adminUser._id,
    });

    // Lifecycle timeline for BR-014
    await LifecycleEvent.create([
      {
        asset: primaryBridge._id,
        eventType: 'REGISTERED',
        title: 'Bridge Registered in State Capital Project Registry',
        description: 'Sabarmati Connector Bridge officially sanctioned and registered under Special Capital Infrastructure Scheme.',
        performedBy: { name: adminUser.name, role: adminUser.role, email: adminUser.email },
        metadata: { budgetINR: 850000000, sanctionedTender: 'AMC-ENG-2021-44' },
        eventDate: new Date('2021-04-15'),
      },
      {
        asset: primaryBridge._id,
        eventType: 'CONSTRUCTION_COMPLETED',
        title: 'Superstructure & Pier Construction Finalized',
        description: 'Physical construction of 620m RCC prestressed box girder superstructure completed by EPC contractor.',
        performedBy: { name: adminUser.name, role: adminUser.role, email: adminUser.email },
        metadata: { concreteVolumeCUM: 18500, pierCount: 14 },
        eventDate: new Date('2023-08-01'),
      },
      {
        asset: primaryBridge._id,
        eventType: 'OPERATIONAL',
        title: 'Bridge Commissioned & Opened for Public Traffic',
        description: 'Statutory load testing of 120 Tons conducted successfully. Formal opening for 6-lane urban traffic.',
        performedBy: { name: adminUser.name, role: adminUser.role, email: adminUser.email },
        metadata: { laneCount: 6, designSpeedKmh: 65 },
        eventDate: new Date('2023-08-15'),
      },
      {
        asset: primaryBridge._id,
        eventType: 'INSPECTION_COMPLETED',
        title: 'Post-Monsoon Structural Quality Audit',
        description: 'Annual comprehensive audit conducted. Ultrasonic testing identified delamination and bearing wear on Pier P-4.',
        performedBy: { name: inspectorUser.name, role: inspectorUser.role, email: inspectorUser.email },
        metadata: { conditionAssessed: 'POOR', ultrasonicResult: 'Spalling depth 45mm' },
        eventDate: new Date('2025-01-10'),
      },
      {
        asset: primaryBridge._id,
        eventType: 'ISSUE_DETECTED',
        title: 'Structural Pier Spalling & Bearing Wear Detected',
        description: 'Concrete spalling and reinforcement exposure on Pier P-4 requires specialized rehabilitation.',
        performedBy: { name: inspectorUser.name, role: inspectorUser.role, email: inspectorUser.email },
        metadata: { severity: 'HIGH', urgency: 'Immediate Work Order Required' },
        eventDate: new Date('2025-01-10'),
      },
      {
        asset: primaryBridge._id,
        eventType: 'MAINTENANCE_ASSIGNED',
        title: 'Rehabilitation Work Order TKT-2025-014 Assigned',
        description: 'Work order assigned to Gujarat Infra Engineering Corp under supervision of Maintenance Officer Vikram Sharma.',
        performedBy: { name: officerUser.name, role: officerUser.role, email: officerUser.email },
        metadata: { ticketId: 'TKT-2025-014', contractor: 'Gujarat Infra Engineering Corp' },
        eventDate: new Date('2025-01-15'),
      },
      {
        asset: primaryBridge._id,
        eventType: 'REPAIR_STARTED',
        title: 'On-Site Hydro-Demolition & Rebar Encasement Commenced',
        description: 'Single lane traffic diversion implemented. High-pressure hydro-demolition and anti-corrosive primer coating active.',
        performedBy: { name: officerUser.name, role: officerUser.role, email: officerUser.email },
        metadata: { ticketId: 'TKT-2025-014', trafficPlan: 'Lane 1 & 2 Diverted' },
        eventDate: new Date('2025-01-20'),
      },
    ]);

    // Active maintenance ticket for BR-014
    await Maintenance.create({
      ticketId: 'TKT-2025-014',
      asset: primaryBridge._id,
      issueType: 'Structural Pier Spalling & Expansion Bearing Wear',
      description: 'Extensive concrete spalling and reinforcement corrosion on Pier P-4 and elastomeric expansion joint misalignment near Abutment A1.',
      priority: 'HIGH',
      assignedTo: 'Gujarat Infra Engineering Corp',
      assignedOfficer: officerUser._id,
      status: 'IN_PROGRESS',
      reportedBy: { id: inspectorUser._id, name: inspectorUser.name, role: inspectorUser.role },
      reportedAt: new Date('2025-01-10'),
      startedAt: new Date('2025-01-20'),
      repairCost: 1450000,
      resolutionNotes: '',
    });

    // Inspection record for BR-014
    await Inspection.create({
      asset: primaryBridge._id,
      inspectionDate: new Date('2025-01-10'),
      inspector: { id: inspectorUser._id, name: inspectorUser.name, role: inspectorUser.role, email: inspectorUser.email },
      condition: 'POOR',
      severity: 'HIGH',
      issueDetected: true,
      remarks: 'Concrete spalling and surface delamination on Pier P-4. Longitudinal crack observed on bearing pedestal.',
      recommendation: 'Immediate structural jacketing with carbon-fiber reinforced polymer (CFRP) and elastomeric bearing pad replacement.',
      assetSpecificInspectionData: {
        structuralCondition: 'Substructure degradation on Pier P-4',
        deckCondition: 'Fair with minor micro-cracking',
        expansionJointCondition: 'Elastomeric joint seal detached',
        loadConcern: true,
        substructureHealth: 'Requires micro-concreting and epoxy grouting',
      },
    });

    // 24 Additional Realistic Assets across Roads, Highways, Bridges
    const additionalAssets = [
      // 10 ROADS
      {
        assetId: 'RD-101',
        assetCode: 'GJ-AHM-RD-101',
        assetType: 'ROAD',
        name: 'S.G. Highway Service Road North',
        description: 'Multi-lane urban service arterial connecting Thaltej Underpass to Vaishno Devi Circle.',
        department: 'Roads & Buildings Department, Ahmedabad',
        district: 'Ahmedabad',
        area: 'Bodakdev - Thaltej',
        location: {
          latitude: 23.0531,
          longitude: 72.5186,
          startLatitude: 23.045,
          startLongitude: 72.515,
          endLatitude: 23.095,
          endLongitude: 72.535,
          address: 'S.G. Highway West Corridor, Ahmedabad',
        },
        assetSpecificDetails: {
          roadNumber: 'MDR-22',
          roadCategory: 'CITY_ROAD',
          startLocation: 'Thaltej Junction',
          endLocation: 'Vaishno Devi Circle',
          lengthKm: 8.4,
          widthMeters: 14.0,
          laneCount: 4,
          surfaceType: 'BITUMINOUS',
        },
        condition: 'GOOD',
        status: 'OPERATIONAL',
        estimatedCost: 125000000,
        lastInspectionDate: new Date('2024-10-14'),
        nextInspectionDate: new Date('2025-04-14'),
      },
      {
        assetId: 'RD-102',
        assetCode: 'GJ-AHM-RD-102',
        assetType: 'ROAD',
        name: 'Ashram Road Arterial Spine',
        description: 'Primary commercial transit road running parallel to the Sabarmati River from Paldi to Usmanpura.',
        department: 'Ahmedabad Urban Development Authority',
        district: 'Ahmedabad',
        area: 'Paldi - Usmanpura',
        location: {
          latitude: 23.0298,
          longitude: 72.5702,
          startLatitude: 23.011,
          startLongitude: 72.565,
          endLatitude: 23.048,
          endLongitude: 72.572,
          address: 'Ashram Road, Central Ahmedabad',
        },
        assetSpecificDetails: {
          roadNumber: 'ODR-12',
          roadCategory: 'CITY_ROAD',
          startLocation: 'Paldi Cross Road',
          endLocation: 'Usmanpura Circle',
          lengthKm: 6.2,
          widthMeters: 22.0,
          laneCount: 6,
          surfaceType: 'BITUMINOUS',
        },
        condition: 'FAIR',
        status: 'OPERATIONAL',
        estimatedCost: 98000000,
        lastInspectionDate: new Date('2024-11-05'),
        nextInspectionDate: new Date('2025-05-05'),
      },
      {
        assetId: 'RD-103',
        assetCode: 'GJ-GND-RD-103',
        assetType: 'ROAD',
        name: 'GIFT City Link Boulevard',
        description: 'Smart city high-capacity dual carriageway accessing Gujarat International Finance Tec-City.',
        department: 'Gandhinagar Urban Development Authority',
        district: 'Gandhinagar',
        area: 'GIFT City Knowledge Corridor',
        location: {
          latitude: 23.1601,
          longitude: 72.6842,
          startLatitude: 23.148,
          startLongitude: 72.671,
          endLatitude: 23.175,
          endLongitude: 72.698,
          address: 'GIFT City Access Way, Gandhinagar',
        },
        assetSpecificDetails: {
          roadNumber: 'GIFT-BLVD-01',
          roadCategory: 'STATE_ROAD',
          startLocation: 'Bhaijipura Junction',
          endLocation: 'GIFT Diamond Tower Gate',
          lengthKm: 5.5,
          widthMeters: 28.0,
          laneCount: 8,
          surfaceType: 'CONCRETE',
        },
        condition: 'EXCELLENT',
        status: 'OPERATIONAL',
        estimatedCost: 240000000,
        lastInspectionDate: new Date('2024-12-12'),
        nextInspectionDate: new Date('2025-06-12'),
      },
      {
        assetId: 'RD-104',
        assetCode: 'GJ-AHM-RD-104',
        assetType: 'ROAD',
        name: 'Sanand Auto Industrial Corridor Road',
        description: 'Heavy vehicle freight road connecting Sanand GIDC manufacturing cluster to State Highway 17.',
        department: 'Gujarat Industrial Development Corporation',
        district: 'Ahmedabad',
        area: 'Sanand Industrial Estate',
        location: {
          latitude: 22.9912,
          longitude: 72.3789,
          startLatitude: 22.975,
          startLongitude: 72.361,
          endLatitude: 23.012,
          endLongitude: 72.395,
          address: 'Sanand GIDC Phase II, Ahmedabad',
        },
        assetSpecificDetails: {
          roadNumber: 'GIDC-SND-08',
          roadCategory: 'DISTRICT_ROAD',
          startLocation: 'Sanand Toll Plaza',
          endLocation: 'Tata Motors Gate 3',
          lengthKm: 11.2,
          widthMeters: 16.0,
          laneCount: 4,
          surfaceType: 'BITUMINOUS',
        },
        condition: 'POOR',
        status: 'UNDER_MAINTENANCE',
        estimatedCost: 165000000,
        lastInspectionDate: new Date('2024-09-18'),
        nextInspectionDate: new Date('2025-03-18'),
      },
      {
        assetId: 'RD-105',
        assetCode: 'GJ-AHM-RD-105',
        assetType: 'ROAD',
        name: 'Dholera SIR Expressway Feeder Road',
        description: 'Greenfield connectivity feeder servicing Dholera Special Investment Region Phase 1.',
        department: 'Dholera Industrial City Development Ltd',
        district: 'Ahmedabad',
        area: 'Dholera Industrial Zone',
        location: {
          latitude: 22.2478,
          longitude: 72.1956,
          startLatitude: 22.235,
          startLongitude: 72.181,
          endLatitude: 22.268,
          endLongitude: 72.215,
          address: 'Activation Area Road A2, Dholera SIR',
        },
        assetSpecificDetails: {
          roadNumber: 'SIR-FEED-01',
          roadCategory: 'STATE_ROAD',
          startLocation: 'Dholera Central Plaza',
          endLocation: 'TP 2 West Boundary',
          lengthKm: 14.5,
          widthMeters: 30.0,
          laneCount: 6,
          surfaceType: 'CONCRETE',
        },
        condition: 'EXCELLENT',
        status: 'OPERATIONAL',
        estimatedCost: 310000000,
        lastInspectionDate: new Date('2024-12-01'),
        nextInspectionDate: new Date('2025-06-01'),
      },
      {
        assetId: 'RD-106',
        assetCode: 'GJ-GND-RD-106',
        assetType: 'ROAD',
        name: 'Gandhinagar Sector 1-11 Central Spine',
        description: 'Tree-lined avenue connecting Secretariat complex to Sector 11 commercial district.',
        department: 'R&B Department, Gandhinagar Capital Project',
        district: 'Gandhinagar',
        area: 'Sector 1 to Sector 11',
        location: {
          latitude: 23.2232,
          longitude: 72.6508,
          startLatitude: 23.211,
          startLongitude: 72.645,
          endLatitude: 23.238,
          endLongitude: 72.661,
          address: 'Road No 3, Gandhinagar',
        },
        assetSpecificDetails: {
          roadNumber: 'GND-RD-03',
          roadCategory: 'CITY_ROAD',
          startLocation: 'Vidhan Sabha Circle',
          endLocation: 'CHH Road Junction',
          lengthKm: 4.8,
          widthMeters: 18.0,
          laneCount: 4,
          surfaceType: 'BITUMINOUS',
        },
        condition: 'GOOD',
        status: 'OPERATIONAL',
        estimatedCost: 65000000,
        lastInspectionDate: new Date('2024-08-20'),
        nextInspectionDate: new Date('2025-02-20'),
      },
      {
        assetId: 'RD-107',
        assetCode: 'GJ-SRT-RD-107',
        assetType: 'ROAD',
        name: 'Surat Ring Feeder Arterial',
        description: 'High-density urban ring road segment linking Udhna Industrial Area to Magdalla Port Access.',
        department: 'Surat Municipal Corporation R&B',
        district: 'Surat',
        area: 'Udhna - Magdalla',
        location: {
          latitude: 21.1458,
          longitude: 72.7845,
          startLatitude: 21.135,
          startLongitude: 72.768,
          endLatitude: 21.162,
          endLongitude: 72.812,
          address: 'Outer Ring Road Segment 4, Surat',
        },
        assetSpecificDetails: {
          roadNumber: 'SMC-ORR-04',
          roadCategory: 'CITY_ROAD',
          startLocation: 'Udhna Teen Rasta',
          endLocation: 'Dumas Road Junction',
          lengthKm: 9.6,
          widthMeters: 24.0,
          laneCount: 6,
          surfaceType: 'BITUMINOUS',
        },
        condition: 'FAIR',
        status: 'OPERATIONAL',
        estimatedCost: 180000000,
        lastInspectionDate: new Date('2024-10-28'),
        nextInspectionDate: new Date('2025-04-28'),
      },
      {
        assetId: 'RD-108',
        assetCode: 'GJ-VAD-RD-108',
        assetType: 'ROAD',
        name: 'Vadodara Alkapuri Bypass Link',
        description: 'Urban congestion relief bypass connecting Gotri Road to Alkapuri railway overbridge approach.',
        department: 'Vadodara Municipal Corporation',
        district: 'Vadodara',
        area: 'Gotri - Alkapuri',
        location: {
          latitude: 22.3106,
          longitude: 73.1678,
          startLatitude: 22.298,
          startLongitude: 73.152,
          endLatitude: 22.325,
          endLongitude: 73.181,
          address: 'Alkapuri-Gotri Link Road, Vadodara',
        },
        assetSpecificDetails: {
          roadNumber: 'VMC-BYP-02',
          roadCategory: 'CITY_ROAD',
          startLocation: 'Gotri Medical College',
          endLocation: 'Alkapuri Station Underpass',
          lengthKm: 5.1,
          widthMeters: 16.0,
          laneCount: 4,
          surfaceType: 'BITUMINOUS',
        },
        condition: 'GOOD',
        status: 'OPERATIONAL',
        estimatedCost: 82000000,
        lastInspectionDate: new Date('2024-07-15'),
        nextInspectionDate: new Date('2025-01-15'),
      },
      {
        assetId: 'RD-109',
        assetCode: 'GJ-NAD-RD-109',
        assetType: 'ROAD',
        name: 'Nadiad-Dakor Pilgrimage Way',
        description: 'Crucial cultural and agricultural district road accommodating major religious foot and bus transit.',
        department: 'Kheda District Panchayat R&B',
        district: 'Nadiad',
        area: 'Nadiad Rural to Dakor',
        location: {
          latitude: 22.7534,
          longitude: 73.1492,
          startLatitude: 22.695,
          startLongitude: 72.865,
          endLatitude: 22.758,
          endLongitude: 73.152,
          address: 'State Road 88 Corridor, Nadiad',
        },
        assetSpecificDetails: {
          roadNumber: 'MDR-88',
          roadCategory: 'RURAL_ROAD',
          startLocation: 'Nadiad Santram Temple Corner',
          endLocation: 'Dakor Ranchhodraiji Gate',
          lengthKm: 32.4,
          widthMeters: 10.0,
          laneCount: 2,
          surfaceType: 'BITUMINOUS',
        },
        condition: 'CRITICAL',
        status: 'CRITICAL',
        estimatedCost: 215000000,
        lastInspectionDate: new Date('2024-06-11'),
        nextInspectionDate: new Date('2024-12-11'),
      },
      {
        assetId: 'RD-110',
        assetCode: 'GJ-AND-RD-110',
        assetType: 'ROAD',
        name: 'Anand Dairy Hub Logistics Link',
        description: 'Heavy dairy tanker transit corridor connecting Amul Processing Plant to National Highway 48.',
        department: 'Anand R&B Division',
        district: 'Anand',
        area: 'Amul Dairy Industrial Zone',
        location: {
          latitude: 22.5645,
          longitude: 72.9567,
          startLatitude: 22.552,
          startLongitude: 72.941,
          endLatitude: 22.578,
          endLongitude: 72.972,
          address: 'Amul Dairy Road, Anand',
        },
        assetSpecificDetails: {
          roadNumber: 'ODR-45',
          roadCategory: 'DISTRICT_ROAD',
          startLocation: 'Anand Railway Goods Shed',
          endLocation: 'NH-48 Samarkha Interchange',
          lengthKm: 7.2,
          widthMeters: 14.0,
          laneCount: 4,
          surfaceType: 'BITUMINOUS',
        },
        condition: 'GOOD',
        status: 'OPERATIONAL',
        estimatedCost: 74000000,
        lastInspectionDate: new Date('2024-09-02'),
        nextInspectionDate: new Date('2025-03-02'),
      },

      // 8 HIGHWAYS
      {
        assetId: 'HW-001',
        assetCode: 'GJ-AHM-HW-001',
        assetType: 'HIGHWAY',
        name: 'NH-48 Ahmedabad-Vadodara Section',
        description: 'Golden Quadrilateral 6-lane access-controlled national highway carrying heavy inter-state commerce.',
        department: 'National Highways Authority of India (NHAI)',
        district: 'Ahmedabad',
        area: 'Ahmedabad - Kheda Boundary',
        location: {
          latitude: 22.8421,
          longitude: 72.7534,
          startLatitude: 22.951,
          startLongitude: 72.632,
          endLatitude: 22.385,
          endLongitude: 73.185,
          address: 'NH-48 Km 112 to Km 154, Gujarat',
        },
        assetSpecificDetails: {
          highwayNumber: 'NH-48',
          corridorName: 'Delhi-Mumbai Industrial Corridor',
          startLocation: 'Ramol Interchange Ahmedabad',
          endLocation: 'Golden Chowkdi Vadodara',
          lengthKm: 102.5,
          laneCount: 6,
          medianType: 'Reinforced Concrete New Jersey Barrier',
          pavementType: 'Flexible Bituminous with SMA Wearing Course',
        },
        condition: 'GOOD',
        status: 'OPERATIONAL',
        estimatedCost: 14500000000,
        lastInspectionDate: new Date('2024-11-19'),
        nextInspectionDate: new Date('2025-05-19'),
      },
      {
        assetId: 'HW-002',
        assetCode: 'GJ-AHM-HW-002',
        assetType: 'HIGHWAY',
        name: 'NE-1 Ahmedabad-Vadodara Expressway',
        description: 'India first access-controlled dual-carriageway concrete expressway (Mahatma Gandhi Expressway).',
        department: 'NHAI Expressway Division',
        district: 'Ahmedabad',
        area: 'C.T.M. Cross Road Toll Way',
        location: {
          latitude: 22.7812,
          longitude: 72.8214,
          startLatitude: 22.985,
          startLongitude: 72.625,
          endLatitude: 22.321,
          endLongitude: 73.195,
          address: 'National Expressway 1, Gujarat',
        },
        assetSpecificDetails: {
          highwayNumber: 'NE-1',
          corridorName: 'Mahatma Gandhi Expressway',
          startLocation: 'Ahmedabad CTM Express Point',
          endLocation: 'Vadodara Toll Plaza',
          lengthKm: 93.1,
          laneCount: 4,
          medianType: 'Continuous Turf Median with Glare Fencing',
          pavementType: 'Rigid Cement Concrete Pavement (PQC)',
        },
        condition: 'EXCELLENT',
        status: 'OPERATIONAL',
        estimatedCost: 18200000000,
        lastInspectionDate: new Date('2024-12-05'),
        nextInspectionDate: new Date('2025-06-05'),
      },
      {
        assetId: 'HW-003',
        assetCode: 'GJ-GND-HW-003',
        assetType: 'HIGHWAY',
        name: 'NH-147 Gandhinagar Gateway Highway',
        description: '6-lane divided state capital highway connecting Ahmedabad Airport Circle to Gandhinagar Sectors.',
        department: 'Roads & Buildings National Highway Division',
        district: 'Gandhinagar',
        area: 'Koba Circle to Sector 0',
        location: {
          latitude: 23.1425,
          longitude: 72.6189,
          startLatitude: 23.082,
          startLongitude: 72.628,
          endLatitude: 23.215,
          endLongitude: 72.639,
          address: 'Airport-Koba-Gandhinagar Road, NH-147',
        },
        assetSpecificDetails: {
          highwayNumber: 'NH-147',
          corridorName: 'Capital Gateway Corridor',
          startLocation: 'Indira Bridge Circle',
          endLocation: 'Chh-0 Circle Gandhinagar',
          lengthKm: 18.2,
          laneCount: 6,
          medianType: 'Curbed Vegetated Median with Solar Illumination',
          pavementType: 'Stone Matrix Asphalt over Granular Base',
        },
        condition: 'EXCELLENT',
        status: 'OPERATIONAL',
        estimatedCost: 3200000000,
        lastInspectionDate: new Date('2024-11-28'),
        nextInspectionDate: new Date('2025-05-28'),
      },
      {
        assetId: 'HW-004',
        assetCode: 'GJ-AHM-HW-004',
        assetType: 'HIGHWAY',
        name: 'NH-27 Saurashtra-North Gujarat Corridor',
        description: 'East-West national transportation backbone handling heavy container transit to Kandla/Mundra ports.',
        department: 'NHAI Regional Office Gandhinagar',
        district: 'Ahmedabad',
        area: 'Bavla - Bagodara Reach',
        location: {
          latitude: 22.7489,
          longitude: 72.2854,
          startLatitude: 22.825,
          startLongitude: 72.355,
          endLatitude: 22.612,
          endLongitude: 72.145,
          address: 'NH-27 Bagodara Section, Ahmedabad District',
        },
        assetSpecificDetails: {
          highwayNumber: 'NH-27',
          corridorName: 'Porbandar-Silchar East-West Corridor',
          startLocation: 'Bavla Bypass',
          endLocation: 'Bagodara Junction',
          lengthKm: 42.0,
          laneCount: 6,
          medianType: 'Steel W-Beam Thrie Crash Barrier',
          pavementType: 'Heavy Duty Dense Bituminous Macadam',
        },
        condition: 'FAIR',
        status: 'OPERATIONAL',
        estimatedCost: 6800000000,
        lastInspectionDate: new Date('2024-08-14'),
        nextInspectionDate: new Date('2025-02-14'),
      },
      {
        assetId: 'HW-005',
        assetCode: 'GJ-SRT-HW-005',
        assetType: 'HIGHWAY',
        name: 'NH-51 Coastal Industrial Highway',
        description: 'Vital economic corridor linking coastal chemical complexes and logistics ports.',
        department: 'Gujarat State Road Development Corporation',
        district: 'Surat',
        area: 'Olpad - Hazira Reach',
        location: {
          latitude: 21.2845,
          longitude: 72.6912,
          startLatitude: 21.325,
          startLongitude: 72.712,
          endLatitude: 21.195,
          endLongitude: 72.654,
          address: 'NH-51 Coastal Belt, Surat',
        },
        assetSpecificDetails: {
          highwayNumber: 'NH-51',
          corridorName: 'Saurashtra-South Gujarat Coastal Belt',
          startLocation: 'Olpad Junction',
          endLocation: 'Mora Cross Road Hazira',
          lengthKm: 34.5,
          laneCount: 4,
          medianType: 'Concrete New Jersey Median',
          pavementType: 'Flexible Bituminous Pavement',
        },
        condition: 'POOR',
        status: 'UNDER_MAINTENANCE',
        estimatedCost: 4500000000,
        lastInspectionDate: new Date('2024-07-22'),
        nextInspectionDate: new Date('2025-01-22'),
      },
      {
        assetId: 'HW-006',
        assetCode: 'GJ-NAD-HW-006',
        assetType: 'HIGHWAY',
        name: 'NH-64 Dandi Heritage Highway',
        description: 'Historic commemorative national highway upgraded for multi-district passenger and freight transit.',
        department: 'NHAI PIU Vadodara',
        district: 'Nadiad',
        area: 'Matar - Kheda Crossings',
        location: {
          latitude: 22.6845,
          longitude: 72.7123,
          startLatitude: 22.752,
          startLongitude: 72.785,
          endLatitude: 22.585,
          endLongitude: 72.624,
          address: 'NH-64 Central Gujarat Heritage Corridor',
        },
        assetSpecificDetails: {
          highwayNumber: 'NH-64',
          corridorName: 'Dandi Heritage Corridor',
          startLocation: 'Kheda Toll Point',
          endLocation: 'Matar Tehsil Border',
          lengthKm: 28.0,
          laneCount: 4,
          medianType: 'Vegetated Island Median',
          pavementType: 'Asphalt Concrete with Polymer Additives',
        },
        condition: 'GOOD',
        status: 'OPERATIONAL',
        estimatedCost: 3100000000,
        lastInspectionDate: new Date('2024-10-10'),
        nextInspectionDate: new Date('2025-04-10'),
      },
      {
        assetId: 'HW-007',
        assetCode: 'GJ-VAD-HW-007',
        assetType: 'HIGHWAY',
        name: 'NH-56 Vadodara-Chhota Udepur Highway',
        description: 'Key eastern mineral and tribal hinterland corridor joining Vadodara to Madhya Pradesh border.',
        department: 'R&B National Highway Division Vadodara',
        district: 'Vadodara',
        area: 'Dabhoi - Bodeli Reach',
        location: {
          latitude: 22.1845,
          longitude: 73.4125,
          startLatitude: 22.254,
          startLongitude: 73.285,
          endLatitude: 22.102,
          endLongitude: 73.612,
          address: 'NH-56 Dabhoi-Bodeli Stretch, Vadodara District',
        },
        assetSpecificDetails: {
          highwayNumber: 'NH-56',
          corridorName: 'Eastern Gujarat Tribal Highway',
          startLocation: 'Kapurai Cross Roads Vadodara',
          endLocation: 'Bodeli City Bypass',
          lengthKm: 48.6,
          laneCount: 4,
          medianType: 'Steel Beam Barrier',
          pavementType: 'Bituminous Concrete',
        },
        condition: 'FAIR',
        status: 'OPERATIONAL',
        estimatedCost: 5200000000,
        lastInspectionDate: new Date('2024-09-14'),
        nextInspectionDate: new Date('2025-03-14'),
      },
      {
        assetId: 'HW-008',
        assetCode: 'GJ-SRT-HW-008',
        assetType: 'HIGHWAY',
        name: 'NH-53 Surat-Hazira Port Deep Highway',
        description: 'Super-heavy multimodal port connector handling steel, petroleum, and container freight from Hazira Port.',
        department: 'NHAI Special Port Connectivity Cell',
        district: 'Surat',
        area: 'Ichhapore - Hazira Port',
        location: {
          latitude: 21.1568,
          longitude: 72.6845,
          startLatitude: 21.185,
          startLongitude: 72.754,
          endLatitude: 21.112,
          endLongitude: 72.632,
          address: 'NH-53 Hazira Port Expressway, Surat',
        },
        assetSpecificDetails: {
          highwayNumber: 'NH-53',
          corridorName: 'Hazira Multimodal Port Corridor',
          startLocation: 'Ichhapore Circle',
          endLocation: 'Adani Hazira Port Complex',
          lengthKm: 21.4,
          laneCount: 8,
          medianType: 'High-Impact Precast Concrete Barrier',
          pavementType: 'Rigid White-Topped Concrete',
        },
        condition: 'GOOD',
        status: 'OPERATIONAL',
        estimatedCost: 4900000000,
        lastInspectionDate: new Date('2024-11-30'),
        nextInspectionDate: new Date('2025-05-30'),
      },

      // 6 MORE BRIDGES (Total 7 bridges including BR-014)
      {
        assetId: 'BR-001',
        assetCode: 'GJ-AHM-BR-001',
        assetType: 'BRIDGE',
        name: 'Sardar Vallabhbhai Patel Bridge',
        description: 'Historical arterial bridge over the Sabarmati River connecting Ellis Bridge area to Jamalpur.',
        department: 'Ahmedabad Municipal Corporation Bridge Wing',
        district: 'Ahmedabad',
        area: 'Jamalpur - Ellis Bridge',
        location: {
          latitude: 23.0185,
          longitude: 72.5742,
          address: 'Sardar Bridge, Sabarmati River, Ahmedabad',
        },
        assetSpecificDetails: {
          bridgeNumber: 'BR-001-SVP',
          bridgeName: 'Sardar Vallabhbhai Patel Bridge',
          crossingType: 'RIVER',
          riverOrCrossing: 'Sabarmati River',
          lengthMeters: 450,
          widthMeters: 22.0,
          laneCount: 4,
          structuralType: 'RCC',
          loadCapacityTons: 80,
        },
        condition: 'GOOD',
        status: 'OPERATIONAL',
        estimatedCost: 320000000,
        lastInspectionDate: new Date('2024-10-15'),
        nextInspectionDate: new Date('2025-04-15'),
      },
      {
        assetId: 'BR-002',
        assetCode: 'GJ-AHM-BR-002',
        assetType: 'BRIDGE',
        name: 'Ellis Bridge Steel Heritage Span',
        description: 'Century-old heritage bowstring arch bridge preserved for pedestrian walkway and emergency transit.',
        department: 'Gujarat Heritage Infrastructure Directorate',
        district: 'Ahmedabad',
        area: 'Paldi - Old City',
        location: {
          latitude: 23.0234,
          longitude: 72.5756,
          address: 'Ellis Bridge Heritage Zone, Ahmedabad',
        },
        assetSpecificDetails: {
          bridgeNumber: 'BR-002-ELB',
          bridgeName: 'Ellis Bridge Heritage Structure',
          crossingType: 'RIVER',
          riverOrCrossing: 'Sabarmati River',
          lengthMeters: 480,
          widthMeters: 12.0,
          laneCount: 2,
          structuralType: 'STEEL',
          loadCapacityTons: 25,
        },
        condition: 'FAIR',
        status: 'OPERATIONAL',
        estimatedCost: 140000000,
        lastInspectionDate: new Date('2024-08-19'),
        nextInspectionDate: new Date('2025-02-19'),
      },
      {
        assetId: 'BR-003',
        assetCode: 'GJ-VAD-BR-003',
        assetType: 'BRIDGE',
        name: 'Golden Bridge Narmada Crossing',
        description: 'Renowned iron/steel girder truss structure connecting Ankleshwar to Bharuch across the Narmada.',
        department: 'R&B Department Bridge Circle Bharuch',
        district: 'Vadodara',
        area: 'Bharuch - Ankleshwar Reach',
        location: {
          latitude: 21.6985,
          longitude: 72.9845,
          address: 'Golden Bridge, Narmada River, Bharuch-Vadodara Belt',
        },
        assetSpecificDetails: {
          bridgeNumber: 'BR-003-GLD',
          bridgeName: 'Historic Golden Bridge',
          crossingType: 'RIVER',
          riverOrCrossing: 'Narmada River',
          lengthMeters: 1412,
          widthMeters: 9.5,
          laneCount: 2,
          structuralType: 'STEEL',
          loadCapacityTons: 40,
        },
        condition: 'FAIR',
        status: 'OPERATIONAL',
        estimatedCost: 650000000,
        lastInspectionDate: new Date('2024-09-08'),
        nextInspectionDate: new Date('2025-03-08'),
      },
      {
        assetId: 'BR-004',
        assetCode: 'GJ-SRT-BR-004',
        assetType: 'BRIDGE',
        name: 'Pandit Deendayal Upadhyay Cable Stayed Bridge',
        description: 'Iconic 4-lane cable-stayed architectural bridge across the Tapi River connecting Athwa to Adajan.',
        department: 'Surat Municipal Corporation Special Projects',
        district: 'Surat',
        area: 'Athwa - Adajan',
        location: {
          latitude: 21.1895,
          longitude: 72.8021,
          address: 'Cable-Stayed Bridge, Tapi River, Surat',
        },
        assetSpecificDetails: {
          bridgeNumber: 'BR-004-PDU',
          bridgeName: 'Pandit Deendayal Upadhyay Cable Bridge',
          crossingType: 'RIVER',
          riverOrCrossing: 'Tapi River',
          lengthMeters: 918,
          widthMeters: 24.5,
          laneCount: 4,
          structuralType: 'COMPOSITE',
          loadCapacityTons: 150,
        },
        condition: 'EXCELLENT',
        status: 'OPERATIONAL',
        estimatedCost: 1450000000,
        lastInspectionDate: new Date('2024-11-12'),
        nextInspectionDate: new Date('2025-05-12'),
      },
      {
        assetId: 'BR-005',
        assetCode: 'GJ-AND-BR-005',
        assetType: 'BRIDGE',
        name: 'Mahi River High-Level Viaduct',
        description: 'Prestressed concrete girder viaduct carrying Anand-Vadodara rail & road alignment above the Mahi River basin.',
        department: 'State Bridge Design Unit',
        district: 'Anand',
        area: 'Vasad Mahi River Gorge',
        location: {
          latitude: 22.4682,
          longitude: 73.0754,
          address: 'Mahi River Viaduct, Vasad, Anand District',
        },
        assetSpecificDetails: {
          bridgeNumber: 'BR-005-MAH',
          bridgeName: 'Mahi River High-Level Viaduct',
          crossingType: 'RIVER',
          riverOrCrossing: 'Mahi River',
          lengthMeters: 840,
          widthMeters: 21.0,
          laneCount: 4,
          structuralType: 'RCC',
          loadCapacityTons: 110,
        },
        condition: 'GOOD',
        status: 'OPERATIONAL',
        estimatedCost: 780000000,
        lastInspectionDate: new Date('2024-10-04'),
        nextInspectionDate: new Date('2025-04-04'),
      },
      {
        assetId: 'BR-006',
        assetCode: 'GJ-VAD-BR-006',
        assetType: 'BRIDGE',
        name: 'Vishwamitri Rail Overbridge Flyover',
        description: '6-lane grade separator flying over Mumbai-Delhi Main Line rail corridor and Vishwamitri riverbed.',
        department: 'Vadodara Municipal Corporation Road Projects',
        district: 'Vadodara',
        area: 'Manjalpur - Akota',
        location: {
          latitude: 22.2854,
          longitude: 73.1895,
          address: 'Akota-Dandia Bazar Flyover, Vadodara',
        },
        assetSpecificDetails: {
          bridgeNumber: 'BR-006-VSH',
          bridgeName: 'Vishwamitri Rail & River Overbridge',
          crossingType: 'RAILWAY',
          riverOrCrossing: 'Western Railway Line & Vishwamitri',
          lengthMeters: 1180,
          widthMeters: 26.0,
          laneCount: 6,
          structuralType: 'COMPOSITE',
          loadCapacityTons: 100,
        },
        condition: 'GOOD',
        status: 'OPERATIONAL',
        estimatedCost: 920000000,
        lastInspectionDate: new Date('2024-12-18'),
        nextInspectionDate: new Date('2025-06-18'),
      },
      {
        assetId: 'BR-007',
        assetCode: 'GJ-SRT-BR-007',
        assetType: 'BRIDGE',
        name: 'Tapi River Causeway Weir Bridge',
        description: 'Low-level submersible weir-cum-bridge regulating upstream water levels while connecting Singanpore to Rander.',
        department: 'Surat Irrigation and Bridge Division',
        district: 'Surat',
        area: 'Singanpore - Rander',
        location: {
          latitude: 21.2245,
          longitude: 72.8123,
          address: 'Singanpore Causeway, Tapi River, Surat',
        },
        assetSpecificDetails: {
          bridgeNumber: 'BR-007-TAP',
          bridgeName: 'Singanpore Weir Causeway Bridge',
          crossingType: 'RIVER',
          riverOrCrossing: 'Tapi River',
          lengthMeters: 550,
          widthMeters: 14.0,
          laneCount: 2,
          structuralType: 'RCC',
          loadCapacityTons: 50,
        },
        condition: 'POOR',
        status: 'UNDER_MAINTENANCE',
        estimatedCost: 390000000,
        lastInspectionDate: new Date('2024-07-30'),
        nextInspectionDate: new Date('2025-01-30'),
      },
    ];

    for (const assetData of additionalAssets) {
      const createdAsset = await Asset.create({
        ...assetData,
        constructionDate: new Date('2020-01-15'),
        operationalDate: new Date('2021-06-01'),
        createdBy: adminUser._id,
      });

      // Seed registration lifecycle event
      await LifecycleEvent.create({
        asset: createdAsset._id,
        eventType: 'REGISTERED',
        title: `${createdAsset.assetType} Registered into State Asset Registry`,
        description: `Official registration entry created for ${createdAsset.name} (${createdAsset.assetId}).`,
        performedBy: { name: adminUser.name, role: adminUser.role, email: adminUser.email },
        metadata: {
          assetCode: createdAsset.assetCode,
          district: createdAsset.district,
          cost: createdAsset.estimatedCost,
        },
        eventDate: new Date('2020-01-15'),
      });

      // Operational event
      await LifecycleEvent.create({
        asset: createdAsset._id,
        eventType: 'OPERATIONAL',
        title: `${createdAsset.assetType} Formally Commissioned`,
        description: `Construction successfully verified. Asset operational under ${createdAsset.department}.`,
        performedBy: { name: adminUser.name, role: adminUser.role, email: adminUser.email },
        metadata: { initialCondition: createdAsset.condition },
        eventDate: new Date('2021-06-01'),
      });

      // Inspection event
      if (createdAsset.lastInspectionDate) {
        await LifecycleEvent.create({
          asset: createdAsset._id,
          eventType: 'INSPECTION_COMPLETED',
          title: `Periodic Field Inspection Audit`,
          description: `Certified inspection logged. Evaluated condition status: ${createdAsset.condition}.`,
          performedBy: { name: inspectorUser.name, role: inspectorUser.role, email: inspectorUser.email },
          metadata: { condition: createdAsset.condition },
          eventDate: createdAsset.lastInspectionDate,
        });

        await Inspection.create({
          asset: createdAsset._id,
          inspectionDate: createdAsset.lastInspectionDate,
          inspector: { id: inspectorUser._id, name: inspectorUser.name, role: inspectorUser.role, email: inspectorUser.email },
          condition: createdAsset.condition,
          severity: createdAsset.condition === 'CRITICAL' ? 'CRITICAL' : createdAsset.condition === 'POOR' ? 'HIGH' : 'NONE',
          issueDetected: createdAsset.condition === 'POOR' || createdAsset.condition === 'CRITICAL',
          remarks: `Routine safety audit conducted. Condition logged as ${createdAsset.condition}.`,
          recommendation: createdAsset.condition === 'CRITICAL' ? 'Immediate closure and structural resurfacing' : 'Routine monitoring',
          assetSpecificInspectionData: {},
        });
      }

      // If asset is under maintenance or critical, create maintenance ticket
      if (createdAsset.status === 'UNDER_MAINTENANCE' || createdAsset.status === 'CRITICAL') {
        const tkt = await Maintenance.create({
          ticketId: `TKT-2025-${Math.floor(1000 + Math.random() * 9000)}`,
          asset: createdAsset._id,
          issueType: createdAsset.assetType === 'BRIDGE' ? 'Scour Protection & Substructure Repair' : 'Bituminous Surface Overlay & Rutting Repair',
          description: `Required rehabilitation maintenance initiated based on field inspection audit results.`,
          priority: createdAsset.condition === 'CRITICAL' ? 'URGENT' : 'HIGH',
          assignedTo: 'State PWD Road Maintenance Division',
          assignedOfficer: officerUser._id,
          status: 'IN_PROGRESS',
          reportedBy: { id: inspectorUser._id, name: inspectorUser.name, role: inspectorUser.role },
          reportedAt: createdAsset.lastInspectionDate || new Date(),
          startedAt: new Date(),
        });

        await LifecycleEvent.create({
          asset: createdAsset._id,
          eventType: 'MAINTENANCE_ASSIGNED',
          title: `Maintenance Work Order Issued (${tkt.ticketId})`,
          description: `Work order assigned to ${tkt.assignedTo} for urgent restorative operations.`,
          performedBy: { name: officerUser.name, role: officerUser.role, email: officerUser.email },
          metadata: { ticketId: tkt.ticketId, priority: tkt.priority },
          eventDate: new Date(),
        });
      }
    }

    console.log('✅ Database seeded successfully!');
    console.log('------------------------------------------------------------');
    console.log('DEMO USER CREDENTIALS:');
    console.log('1. ADMIN:               admin@roadsetu.gov.in / Admin@123');
    console.log('2. FIELD INSPECTOR:     inspector.patel@roadsetu.gov.in / Inspector@123');
    console.log('3. MAINTENANCE OFFICER: engineer.sharma@roadsetu.gov.in / Officer@123');
    console.log('------------------------------------------------------------');
    console.log('PRIMARY DEMO ASSET:');
    console.log('Bridge: BR-014 (Sabarmati Connector Bridge, Ahmedabad - POOR / UNDER_MAINTENANCE)');
    console.log('------------------------------------------------------------');

    return true;
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    throw error;
  }
};

// If run directly via node src/seed.js
if (require.main === module) {
  (async () => {
    await connectDB();
    await seedData();
    await disconnectDB();
    process.exit(0);
  })();
}

module.exports = { seedData };
